### GENERAL SETTINGS ###

# Site settings
title: Zeronet Proxy
description: "A meta ZeroNet proxy site"
blog_name: "Alexander Lewis (AceLewis)"
analytics: UA-70463146-1 #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "https://zeronet.acelewis.com"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

newtab: :target="_blank"
### CONTACT SETTINGS ###
twitter_username: "_AceLewis"
# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: Twitter
    fa_icon: <i class="fa fa-twitter"></i>
    url: https://twitter.com/_AceLewis
  - title: Reddit
    fa_icon: <i class="fa fa-reddit-alien"></i>
    url: https://reddit.com/u/_AceLewis
  - title: Github
    fa_icon: <i class="fa fa-github"></i>
    url: https://github.com/AceLewis
  - title: YouTube
    fa_icon: <i class="fa fa-youtube"></i>
    url: https://www.youtube.com/channel/UCRn4xTmE0IIEPsdt6R0gzcw

contact:
  - title: Twitter
    url: https://twitter.com/_AceLewis
    site_name: _AceLewis
  - title: Reddit
    url: https://reddit.com/u/_AceLewis
    site_name: _AceLewis



# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - Nottingham
    - United Kingdom.
email: N/A
tel: N/A


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Alexander Lewis
    # position: Owner
    text: I am a 4th and final year Physicist at the University of Nottingham.
    img: AceLewisProfilePic.jpg
    social:
      - title: envelope #use for email address
        url: mailto:Removed due to spam
      - title: twitter
        url: http://twitter.com/_AceLewis

# Clients information. Shown on Home and About pages.
clients:
   - name: dribbble
     img: client01.png


# FOOTER ABOUT, Shown in footer on every page
about_footer: "I'm a 4th year Physicist at The University of Nottingham, I am interested in Physics, Maths, Programming and also play a few games in my spare time. I have an interest in data and have made webscrapers to gather information that I can then process, I am currently looking into nice ways to display information easily in infographics using Python. I can code in Matlab, Python and have also made a Steam trading bot in Node.JS."
about_home: "I'm a 4th year Physicist at The University of Nottingham, I am interested in Physics, Maths, Programming and also play a few games in my spare time. I have an interest in data and have made webscrapers to gather information that I can then process, I am currently looking into nice ways to display information easily in infographics using Python. I can code in Matlab, Python and have also made a Steam trading bot in Node.JS."
about_about: "
I am a Physicist at The University of Nottingham currently in my 4th and final year.
I love Physics and also have a big interest in programming, before university I did a bit of
programming in C++ and I enjoyed it however whilst at university I was taught Matlab
a mathematical and statistical language aimed at scientists and engineers, Matlab
further infulenced me into getting into programming as a hobby.
I have done a few projects in Matlab however outside of Physics I do my projects
in other languages such as Python and Node.js as they are free and opensource
so anyone can use what I make in them.
</p><p>
I also love the hardware side technology from CPUs, CCDs, CMOSs and the semiconductors that
build these up I have learned a lot about how they work on the
nanoscale on my course and in my own time. I also
did a summer internship in The University of Nottingham's Spintronics department the main focus was to
see if and how the <a href=\"https://en.wikipedia.org/wiki/Spin_Hall_effect\">Spin Hall effect </a>
could be used to store data for use in computers
in creating long term storage, RAM, and CPU cache. If the Spin Hall effect could be used
in computers the memory would be non-volatile meaning that unlike in traditional RAM
where there would be no need for Memory refresh. Conventional RAM is volatile so
it needs to be \"refreshed\", by using non-volatile memory the power usage would be
reduced. This technology could potentially be used to create faster, cheaper,
more reliable storage that has a much higher storage density however is far from
being used in commercial products.
</p><p>
I also enjoy skiing, cycling, magic tricks, and I used to love playing football but I have not
got the time to play in a team anymore.
</p>"

# Testimonial content. Shown on Home and About page.
testimonial:
    message: "I am a 4th year Physicist at The University of Nottingham, I am interested in Physics, Maths, Programming and also play a few games in my spare time. I have an interest in data and have made webscrapers to gather information that I can then process, I am currently looking into nice ways to display information easily in infographics using Python. I can code in Matlab, Python and have also made a Steam trading bot in Node.JS."
    author: Alex Lewis (AceLewis)
    # position: WEB DESIGNER - BLACKTIE.CO

# CONTACT PAGE
about_contact: "You can contact me on any of the sites listed, note I no longer make Steam Trade bots for people so please do not contact me about purchasing them however if you want a bit of help with Steam's API I will gladly help you out."
where_to_contact_text: "You can contact me on any of the services provided, note I have not included my email address as I do not want to be spammed."
